### ISSUE TITLE
DMA

### ISSUE THREAD

**Issue by zijingsh** [ryanocf/csgo-external-radar#5]
hello im I changed the code to DMA， but I didn't draw anything ，map looking is working 
i dont use NodeJs，can u help  #me？
![IYM 1A%T7T_{0%`~LS}GIGG](https://user-images.githubusercontent.com/28923454/143671086-52bb6cbc-fa82-4a71-8e11-09adf43c8949.png)
![2_NPJW2)6$(F)2UU`7{)ICM](https://user-images.githubusercontent.com/28923454/143671089-0fdc6fd5-29dc-4f54-b6ea-1a6ba47bc301.png)
![QZJA9)2HA7 39T_C{GE_KI8](https://user-images.githubusercontent.com/28923454/143671097-e56e01c0-dfd2-48a0-81ab-1534d70ad182.png)

map is loading but no darw 
THX

**Comment by ryanocf** [comment]
Hey,

did you try to look what your client receives?
Does it get fired every x milliseconds or how do you make sure the client gets constant updates?
This function gets fired every 5 milliseconds by the nodejs server. https://github.com/ryanocf/csgo-external-radar/blob/master/app/public/js/main.js#L11

**Comment by zijingsh** [comment]
yes The problem has already been settled. is gobal question  but  But now character movement on the map becomes dull im dont know why

**Comment by ryanocf** [comment]
Hey,

you could optimize the update rate of the client or add your own interpolation for it.
In my version the client gets every 5ms an update which makes player movement smooth enough on localserver.
If you now have some sort of delay due to your network or other stuff you would need to add your own interpolation and that would at least smooth out the movement even if it's not as precise anymore.
